-- CREATE TABLE - PRODUCT
CREATE TABLE [dbo].[Category](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Name] [NVARCHAR](50) NOT NULL,
	[CreatedDate] [DATETIME2](7) NOT NULL,
	[UpdatedDate] [DATETIME2](7) NULL,
	[CreatedBy] [NVARCHAR](50) NOT NULL,
	[UpdatedBy] [NVARCHAR](50) NULL,
	CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED ([Id] ASC)
 )

 -- CREATE TABLE - CATEGORY
 