-- DATE TIME

SELECT GETDATE()
SELECT CURRENT_TIMEZONE();

SELECT DATEADD(dd,-30,GETDATE())

SELECT CAST(GETDATE() AS DATE)

DECLARE @datetimeStr NVARCHAR(255) = FORMAT(GetDate(), 'yyyy-MM-dd_hh-mm-ss')
print @datetimeStr

SELECT DATEPART(YEAR,GETDATE())
SELECT MONTH(GETDATE()), YEAR(GETDATE()), DAY(GETDATE())

-- RANDOM

SELECT NEWID()

